//History
export const HISTORY_LOAD = "HISTORY_LOAD";
export const HISTORY_REQUEST = "HISTORY_REQUEST";

//Answer
export const ANSWER_LOAD = "ANSWER_LOAD";
export const ANSWER_REQUEST = "ANSWER_REQUEST";
export const CREATE_ANSWER = "CREATE_ANSWER";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const UPDATE_ANSWER_SUCCESS = "UPDATE_ANSWER_SUCCESS";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";

//Log
export const SET_INFO = "SET_INFO";
export const API_ERROR = "API_ERROR";
export const SET_ERROR = "SET_ERROR";
export const HIDE_LOG = "HIDE_LOG";